<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260725113000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create initial Woodpecker training, puzzle and training_puzzle tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE puzzle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source VARCHAR(50) DEFAULT NULL, external_id VARCHAR(120) DEFAULT NULL, fen TEXT DEFAULT NULL, solution JSON NOT NULL, themes JSON NOT NULL, rating INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_puzzle_source_external_id ON puzzle (source, external_id)');
        $this->addSql('CREATE TABLE training (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, first_cycle_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE training_puzzle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, training_id INT NOT NULL, puzzle_id INT NOT NULL, position INT NOT NULL, personal_note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_114A18B0BEFD98D1 ON training_puzzle (training_id)');
        $this->addSql('CREATE INDEX IDX_114A18B0D9816812 ON training_puzzle (puzzle_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_training_puzzle_training_puzzle ON training_puzzle (training_id, puzzle_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_training_puzzle_training_position ON training_puzzle (training_id, position)');
        $this->addSql('ALTER TABLE training_puzzle ADD CONSTRAINT FK_DD1FDF5BEFD10D9 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE training_puzzle ADD CONSTRAINT FK_DD1FDF5B66C3E9B2 FOREIGN KEY (puzzle_id) REFERENCES puzzle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE training_puzzle DROP CONSTRAINT FK_DD1FDF5BEFD10D9');
        $this->addSql('ALTER TABLE training_puzzle DROP CONSTRAINT FK_DD1FDF5B66C3E9B2');
        $this->addSql('DROP TABLE training_puzzle');
        $this->addSql('DROP TABLE training');
        $this->addSql('DROP TABLE puzzle');
    }
}
