<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260829103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user_preference table for persisted settings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, display_name VARCHAR(80) NOT NULL, language VARCHAR(8) NOT NULL, theme VARCHAR(20) NOT NULL, board_light_square VARCHAR(7) NOT NULL, board_dark_square VARCHAR(7) NOT NULL, show_legal_moves BOOLEAN NOT NULL, show_coordinates BOOLEAN NOT NULL, animate_moves BOOLEAN NOT NULL, show_right_click_targets BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9A3C7009A76ED395 ON user_preference (user_id)');
        $this->addSql('ALTER TABLE user_preference ADD CONSTRAINT FK_9A3C7009A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_preference DROP CONSTRAINT FK_9A3C7009A76ED395');
        $this->addSql('DROP TABLE user_preference');
    }
}
