<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260725122500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create app_user table and link trainings to an owner';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON app_user (email)');
        $this->addSql('ALTER TABLE training ADD owner_id INT NOT NULL');
        $this->addSql('CREATE INDEX IDX_D5128A8F7E3C61F9 ON training (owner_id)');
        $this->addSql('ALTER TABLE training ADD CONSTRAINT FK_D5128A8F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE training DROP CONSTRAINT FK_D5128A8F7E3C61F9');
        $this->addSql('DROP INDEX IDX_D5128A8F7E3C61F9');
        $this->addSql('ALTER TABLE training DROP owner_id');
        $this->addSql('DROP TABLE app_user');
    }
}
