<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260725120500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create cycle, cycle_puzzle, training_session and attempt tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cycle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, training_id INT NOT NULL, number INT NOT NULL, status VARCHAR(20) NOT NULL, target_duration_seconds INT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_cycle_training ON cycle (training_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cycle_training_number ON cycle (training_id, number)');
        $this->addSql('CREATE TABLE cycle_puzzle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cycle_id INT NOT NULL, training_puzzle_id INT NOT NULL, position INT NOT NULL, status VARCHAR(20) NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_cycle_puzzle_cycle ON cycle_puzzle (cycle_id)');
        $this->addSql('CREATE INDEX idx_cycle_puzzle_training_puzzle ON cycle_puzzle (training_puzzle_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cycle_puzzle_cycle_training_puzzle ON cycle_puzzle (cycle_id, training_puzzle_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cycle_puzzle_cycle_position ON cycle_puzzle (cycle_id, position)');
        $this->addSql('CREATE TABLE training_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, training_id INT NOT NULL, cycle_id INT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, note TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_training_session_training ON training_session (training_id)');
        $this->addSql('CREATE INDEX idx_training_session_cycle ON training_session (cycle_id)');
        $this->addSql('CREATE TABLE attempt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cycle_puzzle_id INT NOT NULL, training_session_id INT NOT NULL, played_moves JSON NOT NULL, successful BOOLEAN NOT NULL, mistakes_count INT NOT NULL, duration_milliseconds INT NOT NULL, attempted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_attempt_cycle_puzzle ON attempt (cycle_puzzle_id)');
        $this->addSql('CREATE INDEX idx_attempt_training_session ON attempt (training_session_id)');
        $this->addSql('ALTER TABLE cycle ADD CONSTRAINT FK_3F2A028BEFD98D1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cycle_puzzle ADD CONSTRAINT FK_155CD097CC11063 FOREIGN KEY (cycle_id) REFERENCES cycle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cycle_puzzle ADD CONSTRAINT FK_155CD09B2EEE368 FOREIGN KEY (training_puzzle_id) REFERENCES training_puzzle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training_session ADD CONSTRAINT FK_D3D9B59DBEFD98D1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training_session ADD CONSTRAINT FK_D3D9B59DCC11063 FOREIGN KEY (cycle_id) REFERENCES cycle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attempt ADD CONSTRAINT FK_64B99287B44E1655 FOREIGN KEY (cycle_puzzle_id) REFERENCES cycle_puzzle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attempt ADD CONSTRAINT FK_64B99287227A35D5 FOREIGN KEY (training_session_id) REFERENCES training_session (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE attempt DROP CONSTRAINT FK_64B99287B44E1655');
        $this->addSql('ALTER TABLE attempt DROP CONSTRAINT FK_64B99287227A35D5');
        $this->addSql('ALTER TABLE training_session DROP CONSTRAINT FK_D3D9B59DBEFD98D1');
        $this->addSql('ALTER TABLE training_session DROP CONSTRAINT FK_D3D9B59DCC11063');
        $this->addSql('ALTER TABLE cycle_puzzle DROP CONSTRAINT FK_155CD097CC11063');
        $this->addSql('ALTER TABLE cycle_puzzle DROP CONSTRAINT FK_155CD09B2EEE368');
        $this->addSql('ALTER TABLE cycle DROP CONSTRAINT FK_3F2A028BEFD98D1');
        $this->addSql('DROP TABLE attempt');
        $this->addSql('DROP TABLE training_session');
        $this->addSql('DROP TABLE cycle_puzzle');
        $this->addSql('DROP TABLE cycle');
    }
}
