import { test, expect } from '@playwright/test';
import { login } from './helpers/auth';
import { createTraining, attachPuzzles, startCycle } from './helpers/training';
import { playMove } from './helpers/chessboard';
import { puzzles } from './fixtures/puzzles';
test('creates, edits, persists and deletes an isolated training', async ({ page }) => {
  await login(page, 'training');
  const id = await createTraining(page, 'E2E Cycle de vie');
  await page.goto('/dashboard');
  await page.getByRole('button', { name: /^E2E Cycle de vie / }).click();
  await expect(page).toHaveURL(new RegExp(`/trainings/${id}$`));
  await page.getByRole('button', { name: "Modifier l'entraînement", exact: true }).click();
  await page.getByPlaceholder('Ex : Maîtrise des finales de tours').fill('E2E Modifié');
  await page.getByRole('button', { name: /Enregistrer/ }).click();
  await expect(page.getByText('E2E Modifié', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Mes entraînements', exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await page.getByRole('button', { name: /^E2E Modifié / }).click();
  await page.reload();
  await expect(page.getByText('E2E Modifié', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: "Supprimer l'entraînement", exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Supprimer', exact: true }).click();
  await page.getByRole('button', { name: 'Mes entraînements', exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await expect(page.getByText('E2E Modifié', { exact: true })).toHaveCount(0);
});
test('opens the real board and preserves distinct positions when navigating @smoke', async ({ page }) => {
  await login(page, 'training');
  const id = await createTraining(page, 'E2E Navigation');
  await attachPuzzles(page, id);
  await startCycle(page, id, 1);
  await page.getByRole('button', { name: 'Suivant', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Puzzle 2 / 5', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Précédent', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Puzzle 1 / 5', exact: true })).toBeVisible();
  await playMove(page, puzzles[0].solution[0], 1);
  await page.getByRole('button', { name: 'Suivant', exact: true }).click();
  await playMove(page, puzzles[1].solution[0], 1);
});
